# Generated by Django 5.2.7 on 2025-10-19 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("local_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK / On Track"),
                            ("warn", "At Risk"),
                            ("block", "Blocked"),
                        ],
                        db_index=True,
                        default="ok",
                        max_length=8,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("mood", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=32)),
                ("tags", models.CharField(blank=True, max_length=128)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "checked_in_at"],
                        name="checkins_ch_user_id_0fca45_idx",
                    ),
                    models.Index(
                        fields=["user", "status", "local_date"],
                        name="checkins_ch_user_id_d13f5b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "local_date"),
                        name="uniq_checkin_per_user_per_day",
                    )
                ],
            },
        ),
    ]
