# Generated by Django 5.2.7 on 2025-11-09 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "anchor_text",
                    models.CharField(
                        blank=True,
                        help_text="“After I [existing action], I will [tiny behavior] …”",
                        max_length=200,
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("ACTION_ANCHOR", "Action-Anchor"),
                            ("CONTEXT", "Context (time/location)"),
                            ("PERSON", "Person (social)"),
                        ],
                        default="ACTION_ANCHOR",
                        max_length=20,
                    ),
                ),
                (
                    "celebration_note",
                    models.CharField(
                        blank=True,
                        help_text="Short positive phrase to reinforce success (e.g., “Nice!”).",
                        max_length=120,
                    ),
                ),
                (
                    "prompt_variant",
                    models.CharField(
                        choices=[("A", "Anchor wording"), ("B", "Generic reminder")],
                        default="A",
                        help_text="Randomized wording variant for A/B analysis.",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_action",
                    models.CharField(
                        help_text="Existing action (e.g., ‘after I brush my teeth at night’).",
                        max_length=160,
                    ),
                ),
                (
                    "tiny_behavior",
                    models.CharField(
                        help_text="Small behavior (e.g., ‘I will do 3 deep breaths’).",
                        max_length=160,
                    ),
                ),
                (
                    "celebration",
                    models.CharField(
                        blank=True,
                        help_text="How to celebrate (Fogg: emotions wire habits).",
                        max_length=160,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_anchors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="checkins.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HRVReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "rmssd_ms",
                    models.FloatField(blank=True, help_text="rMSSD in ms", null=True),
                ),
                (
                    "sdnn_ms",
                    models.FloatField(blank=True, help_text="SDNN in ms", null=True),
                ),
                (
                    "resting_hr",
                    models.PositiveIntegerField(
                        blank=True, help_text="Resting heart rate in bpm", null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hrv_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("rmssd", models.FloatField(blank=True, null=True)),
                ("sdnn", models.FloatField(blank=True, null=True)),
                ("resting_hr", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("local_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK / On Track"),
                            ("warn", "At Risk"),
                            ("block", "Blocked"),
                        ],
                        db_index=True,
                        default="ok",
                        max_length=8,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("mood", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("source", models.CharField(default="web", max_length=16)),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                ("hrv_rmssd", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "checked_in_at"],
                        name="checkins_ch_user_id_0fca45_idx",
                    ),
                    models.Index(
                        fields=["user", "status", "local_date"],
                        name="checkins_ch_user_id_d13f5b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "local_date"),
                        name="uniq_checkin_per_user_per_day",
                    )
                ],
            },
        ),
    ]
