# Generated by Django 5.2.7 on 2025-10-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="hrv_rmssd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="source",
            field=models.CharField(default="web", max_length=16),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
